name: Build + Test w/clang

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: apt-get dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install wget
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
    - name: Build
      run: |
        CC=clang-16 LLVM_CONFIG=llvm-config-16 bash -x build.sh stage3
    - name: Test
      run: |
        CC=clang-16 python3 test.py  -v
